### ISSUE TITLE
google says crawl errors. 

### ISSUE THREAD

**Issue by jpca999** [vuejs/vue-hackernews-2.0#101]
I tried to run this app on my server, but google couldnt crawl the site. anybody knows why so ?

![image](https://cloud.githubusercontent.com/assets/1026325/21171444/2f6bacec-c19a-11e6-917e-3456d4ce74a2.png)

![image](https://cloud.githubusercontent.com/assets/1026325/21171722/b8df25ac-c19b-11e6-94e3-dc14111f1946.png)

**Comment by ktquez** [comment]
@jpca999 
Your app is offline.
