### ISSUE TITLE
Vue.util.extend()

### ISSUE THREAD

**Issue by app-sparkler** [vuejs/vue-hackernews-2.0#103]
This project is with Vue 2.0, however, I'm not able to find the `Vue.util` in _API_ or _Guides_.  This line of code is in the _app.js_ file:

```
//app.js
...
const app = new Vue(Vue.util.extend({
  router,
  store
}, App))
...
```

Please advise where it is coming from.

Thanks!

**Comment by yyx990803** [comment]
That's an internal method, just a property mixing method. It can be replaced with Object.assign. I've avoided using it now.
