### ISSUE TITLE
Proper HTTP status code managing

### ISSUE THREAD

**Issue by vanesyan** [vuejs/vue-hackernews-2.0#11]
Is there any way to properly managing HTTP status code, such as 404, 500, etc. with SSR?

**Comment by LinusBorg** [comment]
Can you elaborate what you mean by that?

I would assume that would be the job of the server (e.g. express) rather than vue-ssr?

**Comment by yyx990803** [comment]
If you want to return 404, you can:

1. Detect that no components are matched in `src/server-entry.js`, and set a corresponding field on the render context, e.g. `context.code = 404`

2. In the server handler, end the request with a 404 if it finds that code.

We will incorporate that into the example soon.

**Comment by vanesyan** [comment]
@LinusBorg if you look into source code, you'll see that express handle all request in one route `app.get('*', ...)`, while path context to `vue-router` and then `vue-router` handle routing on its side, if no routing path matched it redirect to `/top`, but on this stage I want to return proper 404 page and code status :)

**Comment by vanesyan** [comment]
@yyx990803 Thanks for the answer. Will try it :)

**Comment by vanesyan** [comment]
I'll closed it as issue is resolved

**Comment by BorjaRafols** [comment]
@yyx990803 This does not cover all the cases. For example in your demo look at the following route:
https://vue-hn.now.sh/user/tentase5rtsdfgdfgsdfgsdfg

In that case, we have a matching component, but not a valid username. This should be throwing a 404 on the server with the 404 page from the vueJS app rendered. In your demo it's returning a 200.

That's pretty bad for Search Engines as you will them them to index every page even thought it does not have content.

I hope I explained myself :)
