### ISSUE TITLE
question about 'store.replaceState(window.__INITIAL_STATE__)'

### ISSUE THREAD

**Issue by freeozyl80** [vuejs/vue-hackernews-2.0#110]
why should I replace state?  I think the status isn't changed after the server render.

Thanks...   :D

**Comment by LinusBorg** [comment]
Without that, the state on the client is empty, and therefore, the client-side virtualDOM will likely be different to the server-rendered HTML DOM. 

When that happens, Vue can't reliably detect which DOM element represent which component, and therefore has to re-render the whole APP again in the browser - which renders the SSR useless.

**Comment by freeozyl80** [comment]
@LinusBorg  thanks a lot;  I begin to realize that the server render's result is static, So 'store.replaceState' is Just like 'app.$mount()" which activate the server render to client render.
