### ISSUE TITLE
Service Worker does not cover the main html page itself

### ISSUE THREAD

**Issue by matthiasg** [vuejs/vue-hackernews-2.0#117]
The service worker does not enable dynamic caching and does not cache '/' or '/index.html' manually either. therefore the application hosted in the demo or run locally is not really offline capable.

**Comment by yyx990803** [comment]
It does not claim to be offline capable, mostly because HN is time sensitive and almost pointless to make offline-usable, but PR welcome.

**Comment by matthiasg** [comment]
@yyx990803 no problem per se, just confused that it included it partially ready :) will do a PR when i get around to it. its mostly a small change in server.js to serve rendered template via `GET /dist/index.html` and another to not exclude index.html from serviceworker anyway. but I am not happy with this service worker implementation since it doesnt do proper versioning etc. When I implemented something proper I will share,
