### ISSUE TITLE
No respond on windows when visit `localhost:8080`

### ISSUE THREAD

**Issue by leohxj** [vuejs/vue-hackernews-2.0#119]
Similar issue is #98 

我还是用中文吧：
Mac 下运行正常，  windows 下 `npm run dev` 无报错信息。但 `renderStream` 绑定的事件都没有触发，怀疑 `vue-server-renderer` 组件在 windows 下兼容问题。

本地环境:
- windows7
- node: 6.9.2

**Comment by leohxj** [comment]
SSR 渲染的时候，网络访问  https://hacker-news.firebaseio.com 异常，阻塞了响应的返回，所以页面一致没有响应。

相关代码在 `src/server-entry.js` 中的 `return component.preFetch(store)`  触发，调用 `src/store/api.js` 中的 `fetch` 方法，最终由于 网络问题 阻塞 `Promise` 返回。

解决的方法，可以使用  `Proxifier` 代理 `node.exe` 使其走一个可用的代理访问请求。

**Comment by DanielWLam** [comment]
跟网络有关？明明是这个haker-news的网址不存在，即使用proxy做代理，这个网址还是不存在吧？ @

**Comment by leohxj** [comment]
@DanielWLam 
这就很尴尬了，之前我本地启动的时候，是这个地址。
不然你本地跑一下看看，firebase走的什么地址，然后有无问题。

**Comment by DanielWLam** [comment]
@leohxj 我换到ubuntu环境就没问题了，应该还是代码兼容问题吧？
