### ISSUE TITLE
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by billwing** [vuejs/vue-hackernews-2.0#127]
I built with `utils.js` as `vue-loader config` from `vue-webpack-boilerplate`. 
And `build:client` is OK. But `build:server` show errors:

    ERROR in ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-dea5eaf8!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
    Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch
    ...

**Comment by yyx990803** [comment]
The build configurations are different between the projects, copy-pasting is not guaranteed to work.
