### ISSUE TITLE
HMR issue

### ISSUE THREAD

**Issue by QuentinFchx** [vuejs/vue-hackernews-2.0#13]
Hi,

I'm pretty new to all the HMR + vuex stuff, that's why i'm playing with this demo.
However, I found this strange behaviour:
Let's take the `App.vue` component.
If I update the text in one of the `router-link` node, HMR works and the text node gets updated
```
<router-link to="/top">TopFoo</router-link>
````
If I add a HTML node right before, HMR works as expected, the node is prepended
```
<h1>Bar</h1>
<router-link to="/top">TopFoo</router-link>
```
But if I update the text within that new tag, HMR does not care at all
```
<h1>BarBaz</h1>
<router-link to="/top">TopFoo</router-link>
```
Is it intended?

**Comment by yyx990803** [comment]
This seems to be a general bug in `vue-hot-reload-api`, tracking there instead: https://github.com/vuejs/vue-hot-reload-api/issues/35
