### ISSUE TITLE
Warnings in prod but not dev?

### ISSUE THREAD

**Issue by jazoom** [vuejs/vue-hackernews-2.0#135]
In `webpack.base.config.js` there is this:

```
performance: {
    hints: process.env.NODE_ENV === 'production' ? 'warning' : false
}
```

Should `'warning'` and `false` be around the other way, or am I missing something? I think the warnings would be more useful in development than in production.

**Comment by jazoom** [comment]
Oh, is 'production' referring to a warning during a build for production? In that case, this does make sense.

**Comment by LinusBorg** [comment]
Yep. During development, you don't want to see those warnings all of the time, so they are turned off.

But when building for production, you want to get warnings about bundles that are too big.

This warning will not log to console when running in the browser, just during webpack's build phase.
