### ISSUE TITLE
SSR not rendering styles

### ISSUE THREAD

**Issue by MarkPieszak** [vuejs/vue-hackernews-2.0#144]
It seems like the server-rendered view has no styles applied to it and flickers from the view below, to the fully rendered & styled client-side one afterwards.

Is this default behavior with Vue perhaps?

![image](https://cloud.githubusercontent.com/assets/2574412/23857243/fe024718-07d2-11e7-9893-2f90ad992201.png)

**Comment by stephan281094** [comment]
Did you run this in production or development mode (`npm run start` or `npm run dev`)? In development mode, Webpack creates style tags with javascript to allow hot reloading CSS. In production mode, the CSS should be bundled into its own CSS file.

**Comment by yyx990803** [comment]
Dev mode requires JavaScript... obviously. In production mode the CSS doesn't rely on JavaScript.

**Comment by MarkPieszak** [comment]
Ahh ok, I wasn't sure if it was being passed in with the HTML itself and not being parsed correctly.
Makes sense thanks Evan :+1:
