### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by zuoye520** [vuejs/vue-hackernews-2.0#146]
尤老湿，你好！ 
我拉取vue-hackernews-2.0 做ssr的时候 引入一些第三方插件，运行报window is not defined,但是第三方插件明确指出已经支持vue2了，
不知道有没有好的解决办法？？ 
还是只有提供插件的作者去解决此问题？？？

**Comment by yyx990803** [comment]
当然是找插件作者。支持 vue 2 !== 支持 ssr
