### ISSUE TITLE
 Error css not extract in proudction after update to vue 2.2.4

### ISSUE THREAD

**Issue by tronghiep92** [vuejs/vue-hackernews-2.0#147]
Today new [commit](015e059ef1a66ded7562cde8e47985717b63b412) update to use 2.2.4.
I see css not extract in production.
File [app.js](https://vue-hn.now.sh/dist/app.03e2aa36c7cb105b63d8.js)
![1](https://cloud.githubusercontent.com/assets/4768095/23942568/49d4f9a6-099f-11e7-944d-50353891c1c1.png)
![2](https://cloud.githubusercontent.com/assets/4768095/23942571/4cc15600-099f-11e7-8dc7-be915b46b28d.jpeg)
In my project file app.js from 800kb to 1.2mb :(

**Comment by yyx990803** [comment]
The new setup removed CSS extraction on purpose because it now supports webpack code splitting.

**Comment by tronghiep92** [comment]
I cannot debug css in chrome. Something's wrong with that source map.
