### ISSUE TITLE
[Help] When use vuex store.registerModule ssr response incorrect

### ISSUE THREAD

**Issue by bodyno** [vuejs/vue-hackernews-2.0#155]
When I use store.registerModule like this

![image](https://cloud.githubusercontent.com/assets/5443058/24400903/c39022ee-13e4-11e7-9709-1ec5e4429814.png)

Then ssr response like this. The component vue code is correct.

![image](https://cloud.githubusercontent.com/assets/5443058/24400893/bc11ca22-13e4-11e7-8026-972493e50bf0.png)

How to do with it? Help

**Comment by bodyno** [comment]
There is no one answered. Closed.

**Comment by sirlancelot** [comment]
There is a guide now for SSR that may help you: https://ssr.vuejs.org/ Keep in mind that Vue's issue list isn't for questions. You can ask the Discord community: https://vue-land.js.org/ and get more eyes to help you.
