### ISSUE TITLE
vuex store state function-properties are undefined only inside the browser

### ISSUE THREAD

**Issue by foosx** [vuejs/vue-hackernews-2.0#165]
Basically any form of `fun` is being removed and not defined in the browser, while still being accessible in the server side rendering.
```javascript
new Vuex.Store({
  state: {
    fun: () => false,
    bar: { fun: function(){ return false} },
  ...
```

**Comment by yyx990803** [comment]
Vuex state should be serializable (i.e. if it will be discarded during `JSON.stringify` then it is not safe to use).
