### ISSUE TITLE
Accessing router instance in Vuex store

### ISSUE THREAD

**Issue by rdunk** [vuejs/vue-hackernews-2.0#171]
With the new best practices for SSR implemented into this app, the store and router instances are generated by `createStore()` and `createRouter()` respectively. As importing the router instance is no longer as simple as `import router from '../router'`, is it still possible to achieve programmatic router navigation in the Vuex store?

Apologies if this is not the correct place for this question!

**Comment by yyx990803** [comment]
you can pass the router instance as part of the action payload.

**Comment by trajano** [comment]
Actually I was thinking that since `vue-router` would be quite fundamental, it may be good to have it as part of the data by default rather than explicitly passing it in.

**Comment by trajano** [comment]
@justin-schroeder that's a nice find not sure if it is in the documentation but it really should be.

**Comment by pajtai** [comment]
@yyx990803 How would you pass the router in if you are calling a dispatch from `beforeRouterEnter`? `this` is undefined, and it doesn't look like the router is passed with `to`, `from`, or `next`?

**Comment by ntraykov** [comment]
@justin-schroeder I've tried this. It's awesome!

**Comment by kamgasimo** [comment]
@rdunk You can add a router property to Vue after calling the createRouter() method
`const router = createRouter()`
  `Vue.router = router`
Then in your store import Vue and use the router as `Vue.router`
That's what worked for me. I prefer this than to pass the router instance every time I'm dispatching an action

**Comment by bmbmjmdm** [comment]
To add onto @kamgasimo's comment, you can also make sure everything using `Vue.router` is reactive by changing it like so:
`const router = createRouter()`
`Vue.router = Vue.observable(router)`

**Comment by Delphn** [comment]
As @yyx990803 said, I tried this:
`this.$store.dispatch('action', { customObject, router: this.$router })`

And this way you can access `router` from **store** like this:
`action ({ state, commit}, payload) {
  const router = payload.router
}`

**Comment by Chuiantw1212** [comment]
@justin-schroeder This did not work well for me. I've tried it, and nothing appears in my store.state.

**Comment by andersonmadeira** [comment]
Well, @Delphn I tried that and I get a weird
Uncaught (in promise) undefined
Just before calling router.push({ name: 'route'})
Any ideas on that?
@yyx990803 

EDIT: I even tried to bind the function before sending to the action's payload:

```js
onUserLogout() {
  const routerPush = this.$router.push.bind(this.$router);
  this.userLogout({ router: { push: routerPush } })
},
```

EDIT2:
My bad, it really works, I just forgot to call some function here first in my code.
