### ISSUE TITLE
Lighthouse: respond with a 200 when offline

### ISSUE THREAD

**Issue by addyosmani** [vuejs/vue-hackernews-2.0#173]
Vue HN almost gets a 100 on desktop Lighthouse but currently fails just one audit: responding with a status code of 200 when offline.

![image](https://cloud.githubusercontent.com/assets/110953/25673452/50cb910c-2fec-11e7-976a-09b9c3de0de9.png)
![image](https://cloud.githubusercontent.com/assets/110953/25673526/96e5f98e-2fec-11e7-9365-ec3c16431031.png)

Minor thing, but if anyone gets a chance to look at it would boost the score :)

**Comment by StevenYuysy** [comment]
I simply try to solve in this way: https://github.com/vuejs/vue-hackernews-2.0/pull/175
As you can see, it pass the LightHouse test.
![2017-05-04 3 40 42](https://cloud.githubusercontent.com/assets/11738111/25694466/5b6fd532-30e1-11e7-8f51-26cecc63102f.png)

**Comment by yyx990803** [comment]
After merging #175 :)

![screen shot 2017-05-06 at 9 25 05 pm](https://cloud.githubusercontent.com/assets/499550/25772646/7fb39d9e-32a2-11e7-802e-67095ecc04a9.png)

**Comment by addyosmani** [comment]
\o/

**Comment by pjar** [comment]
So what I'm doing wrong here? 
<img width="1237" alt="screenshot 2017-05-22 19 47 12" src="https://cloud.githubusercontent.com/assets/236458/26321550/82fc38f8-3f27-11e7-830a-3d7654c382e3.png">

**Comment by ram-you** [comment]
@pjar Worse than you, **Performance=0** 
![capture d ecran_2017-05-23_11-07-06](https://cloud.githubusercontent.com/assets/3125972/26349672/5749aa7a-3fa8-11e7-9dd4-7727cef8b5a7.png)

**Comment by ashwinkshenoy** [comment]
Is there a way to do the same using workbox webpack plugin with SSR?
