### ISSUE TITLE
改为koa2之后js静态资源加载不出来

### ISSUE THREAD

**Issue by JerroldLee** [vuejs/vue-hackernews-2.0#18]
遇到一个很奇怪的现象，我将项目改成了koa2，渲染首屏的时候，js静态资源路径是没错的，直接在网页打开js是能访问到的，但查看控制台，js静态资源请求结果返回404，js也没有正常加载到首屏页面，导致程序无法正常执行

补充：这个问题解决了，不过css没有正常插入页面，是stylus loader问题吗？

**Comment by yyx990803** [comment]
... 你这个完全是你自己的问题了，我又不知道你改了什么
