### ISSUE TITLE
Auth in SSR

### ISSUE THREAD

**Issue by dinho-afsn** [vuejs/vue-hackernews-2.0#183]
Can anyone tell me if there is any way to sign in with SSR.
How can I authenticate user rum with vue SSR?

i try 

  if (route.matched.some(record => record.meta.requiresAuth)) {

When I put the token manually in the state it works perfectly.
Now when, I remove the manual token and go through the login. The state changes the token but the routes do not work

Does anyone have any login material?

tanks!

**Comment by dmitry7887** [comment]
I have same question. Could you please describe SSR and authenticate best practices?

**Comment by fareesh** [comment]
Could use some advice here too

**Comment by wmui** [comment]
I hava the same quesiton too

**Comment by Zedonboy** [comment]
Alright see what am thinking...
1.In the login page use axios get users credentials send to server.
2. pass credentials in the server context object. now use the credentials dispatch a login event
3. then the Store calls the models asychronously, pass the credentials to the models
4. models performs query if fail, tell the store continue in a reverse order. if success fetch the necessary data
5. send data to store and continue. (Heaves) now Vue-SSR server sends a vue instance to axios
@dinho-afsn @dmitry7887 @fareesh @wmui @mikekidder  please help ourselves how do we tell
vue to render the new Vue instance in the response object. or pass it to router object to see it as new component to be rendered

**Comment by dmitry7887** [comment]
I used my cookie for the SSR. 
1. To do that I added cookie parser to server.js  
`const cookieParser = require('cookie-parser')  `

2. Then need to add cookies from client request to context (before "renderToString"):
```

const context = {
        title: 'APP', // default title
        url: req.url,
        cookies: req.cookies
    }
renderer.renderToString(context, (err, html) => {
.....

```
3. Now I can check cookies variable and use user auth token for axios requests. I added to entry-server.js this lines:
```
if (context.cookies.Authorization) {
     store.state.token = context.cookies.Authorization;
     router.push(url)
} else {
     router.push("/login")
}

```

**Comment by josec89** [comment]
@dmitry7887 I could make it work only when `runInNewContext: true` which is highly discouraged, because the context is server-global and my token is not refreshed until I restart the server... did you face the same problem?

**Comment by dmitry7887** [comment]
@josec89 I have not this problem.

**Comment by edugrip** [comment]
@dmitry7887 , can you suggest How to check if the `url`  requires Authentication or not? Because it is not giving full router's to path object. It just returns a string e.g. `/top`... To clarify more, for e.g. on client I can check with router.beforeeach(to, from, next).... and then `to.meta.requiresAuth` gives me whether it requires auth or not.  How can I get the meta property of the requested url?

**Comment by edugrip** [comment]
Second how do you forward cookies from your  api-server to the browser?
