### ISSUE TITLE
Cannot use native objects

### ISSUE THREAD

**Issue by wmui** [vuejs/vue-hackernews-2.0#186]
In vue components,like this use:
```

  created(){
    console.log(document)
  }
```
result:  500 | Internal Server Error
How do I solve

**Comment by stephan281094** [comment]
`document` is only available in browsers. Since Nuxt uses server side rendering (SSR), it doesn't recognise this property and throws an error.
You can solve this by using the `mounted()` method instead.

**Comment by wmui** [comment]
@stephan281094 
I tried, still won't do,but still thank you

**Comment by stephan281094** [comment]
In that case, do you have any error message/ stack trace?

**Comment by yyx990803** [comment]
http://ssr.vuejs.org/en/universal.html
