### ISSUE TITLE
如何在多页应用中使用ssr?

### ISSUE THREAD

**Issue by miyalee** [vuejs/vue-hackernews-2.0#187]
如题，不用router，有多个App.vue和app.js。
并没有想到好用的方案。在entry-server.js试图通过URL根据路径判断应该返回哪个实例，在entry-client.js中怎么知道当前URL呢？怎么操作该挂在的app？server.js又该如何操作？

**Comment by StevenYuysy** [comment]
为什么不用 router

**Comment by miyalee** [comment]
因为有很多入口

**Comment by yyx990803** [comment]
理论上没有这个必要。多入口个多个顶层路由没有本质区别。

**Comment by chenwenxian** [comment]
@yyx990803 在webpack.client.config.js、webpack.server.config.js文件entry入口只能写一个.js入口么？能否可以加多入口的？

**Comment by NoraGithub** [comment]
@yyx990803 请问什么叫做 多个顶层路由组件 组件呢？可以简单写一个伪代码吗？（尬笑

我的需求是 同一套代码通过根据环境变量生成两套代码分别作用于PC和移动端（类似import create-api）。您的解决方案是否不太match？

**Comment by DirtyWhite** [comment]
@NoraGithub 之前遇到这个问题，解决方案是使用gulp来扫描入口文件，然后使用命令行插件传入参数来分入口执行多次build。
有点不太理解尤大的多入口和多个顶层路由没有区别。可能对于服务端渲染过程是没有区别的，但是到客户端渲染过程，同一个入口的代码会被打包到一起进行下载，不同入口代码体积显然会小很多。是不是可以使用异步路由的方式来拆分顶层路由，这样可以一定程度减小体积。但是异步路由对于服务端渲染的影响是什么样的，这个我得验证一下。

**Comment by DirtyWhite** [comment]
验证完了，异步组件都会被ssr忽略，无法解决这个问题。

**Comment by leon776** [comment]
多次build+1，vue-ssr-client-manifest.json会把所有的entry都放到initial里面

**Comment by zwmmm** [comment]
这个问题 有没有好的解决方案 是否可以不适用自动注入 该用手动手动注入对应的资源

**Comment by Gourdbaby** [comment]
我也有这样的需求 ，请问谁有好的思路，就想多页面开发，不想使用路由

**Comment by wensiyuanseven** [comment]
> 我也有这样的需求 ，请问谁有好的思路，就想多页面开发，不想使用路由

多页面开发 如果想更好的seo 可以从预渲染的角度来考虑
