### ISSUE TITLE
Page Hangs if too many comments

### ISSUE THREAD

**Issue by w10036w** [vuejs/vue-hackernews-2.0#19]
Reproduction:
test link: https://vue-hn.now.sh/item/12405698

Description:
due to >800 comments, WebSocket keeps loading all comments one by one. Page then shows no response to user controls. This is for the first time rendering without cache.

Suggestion:
lazy load comments / paging fetch

**Comment by yyx990803** [comment]
That's a limitation of how the Firebase API is exposed... there's no API that allows fetching all comments in one go so we can only fetch the data in a waterfall fashion.

But lazy loading on scroll would be a good idea.

**Comment by yyx990803** [comment]
Improved comments loading by fetching all comments first and then render once.
