### ISSUE TITLE
Client bundle size

### ISSUE THREAD

**Issue by minimok** [vuejs/vue-hackernews-2.0#2]
Is it possible to get the bundle size down. This loads around 300KB into the browser. Surely that's not necessary?

**Comment by yyx990803** [comment]
The while bundle is around ~250kb and the majority of it is from Firebase (~140kb).

**Comment by minimok** [comment]
Ah. OK. I'm experiencing similar question with your basic SSR example ('vue-ssr-demo-master') After build the client bundle is 174KB, same size as the server bundle. The client code for this example should surely be miniscule??? I'm obviously not understanding this.

**Comment by yyx990803** [comment]
The ssr demo has no production-oriented config, so it isn't compressing as efficiently as this one.
