### ISSUE TITLE
Optimization: don't transpile natively supported ES6 features on the server

### ISSUE THREAD

**Issue by nemtsov** [vuejs/vue-hackernews-2.0#201]
Please ignore and close this issue if you're already aware of this.

It's possible to use [.babelrc env options](https://babeljs.io/docs/usage/babelrc/#env-option) to define a `client` and `server` environments in `.babelrc` and then in the `vue-loader`'s `options.loaders.js` use: `babel-loader?forceEnv=<client_or_server>` to prevent babel from transpiling ES6 features on the server, which Node.js natively supports.

The advantage is potentially a more efficient server side render. The disadvantage -- running a slightly different builds on the client and server.

If this is interesting, I can put together a PR.

Thanks for your incredible work!

**Comment by yyx990803** [comment]
I'm actually aware of that, but at this moment, ES201x features in V8 are not necessarily faster than their ES5 counterparts. In addition, leaving ES201x features in final code means we need to use either Babili or UglifyJS 3 for minification. Babili is slow, and the webpack uglify plugin hasn't upgraded to UglifyJS 3 yet.

I think we will probably do this when UglifyJS 3 has been integrated into the webpack uglify plugin. But thanks for the suggestion and offering to help!
