### ISSUE TITLE
__webpack_hmr 404 Not Found

### ISSUE THREAD

**Issue by miyalee** [vuejs/vue-hackernews-2.0#204]
求助！
项目放到测试环境出现这个报错，也不嫩在自动更新了，改动是leader在根目录下放了两个vue project，目录结构：

- frontend

    - common 我的项目

    - dms 另一个项目

中间的各种代理我不太懂，反正最后运行服务端口是8004，node端口6002，查看效果12358。
运行后文件各种404
leader说原来的静态文件url前需要加上／common，研究了半天做了如下改动
```
//webpack.base.config.js
module.exports = {
    devtool: isProd ? false : '#cheap-module-source-map',
    output: {
        path: path.resolve(__dirname, '../dist'),
        publicPath: '/common/dist/',
        filename: '[name].[chunkhash].js'
    },
```  
```
//server.js
app.use('/common/assets', serve('./src/assets', true))
```
```
//template.html
<link rel="shortcut icon" sizes="48x48" href="/common/assets/images/favicon.ico">
```

现在不再404了，除了__webpack_hmr。。。。这个试了各种方法也没成功，包括
`clientConfig.entry.app = ['webpack-hot-middleware/client?path=/common/__webpack_hmr&timeout=10000&reload=true', clientConfig.entry.app]`
或者
`clientConfig.entry.app = 'webpack-hot-middleware/client?path=http://'+sitename+':'+'12358'+'/__webpack_hmr'`
或者
`clientConfig.entry.app = 'webpack-hot-middleware/client?path=http://loclhost:6002/__webpack_hmr'`

虽然不影响开发，但是每几秒一个error，而且不能自动更新，很蛋疼，不知道怎么改才好求各位帮助。。。

ps：怕自己描述不清楚，在详细说下运行过程
后台是python 首先 运行`python.manage.py runserver 8004`
然后到frontend/common 目录下运行` PORT＝6002 npm run dev`
最后在https://sitename:12358/login/查看效果login页效果。。。

跪求解决方法

**Comment by miyalee** [comment]
已解决
```
clientConfig.entry.app = ['webpack-hot-middleware/client?path=/common/__webpack_hmr', clientConfig.entry.app]
```
```
app.use(require('webpack-hot-middleware')(clientCompiler, {
        path: '/common/__webpack_hmr'
    }))
```

**Comment by sijinglei** [comment]
clientCompiler这个是什么鬼？

**Comment by qianlongo** [comment]
我也遇到这样的问题，不能热更新，但是按照@miyalee 你的方式，还是404

**Comment by thezk0711** [comment]
eval('alert(1)')
