### ISSUE TITLE
Less not compatible with V2.3

### ISSUE THREAD

**Issue by andylei18** [vuejs/vue-hackernews-2.0#214]
After packing, run and find that style is not compressed

**Comment by john-ko** [comment]
did you try `npm install -D less less-loader` ?

**Comment by valentinvieriu** [comment]
@andylei18 did you've tried that? The less loader does not come by default installed.
Also you need to add 
`<style lang="less">` in your code

**Comment by andylei18** [comment]
@valentinvieriu I did it long ago, but it's the same

**Comment by andylei18** [comment]
@john-ko That's what I did, but it turned out that way
