### ISSUE TITLE
The live demo is down

### ISSUE THREAD

**Issue by DannyFeliz** [vuejs/vue-hackernews-2.0#22]
![screen shot 2016-09-10 at 12 24 17 pm](https://cloud.githubusercontent.com/assets/5460365/18411954/9c327dda-7751-11e6-80f0-d68fe74545f5.png)

**Comment by Outpox** [comment]
Currently working for me!

**Comment by LinusBorg** [comment]
@DannyFeliz 

Thanks for reporting this issue. Can you please provide any additional information? (OS, node version, things you did to run it ..) 

A "it does not work" screenshot is not very helpful in identifiying the issue

**Comment by Outpox** [comment]
@LinusBorg: I'd say the title "The live demo is down" is self explanatory, he tried accessing [this page](https://vue-hn.now.sh/) and it seems he had an error with it.

**Comment by LinusBorg** [comment]
Oh. My mistake, sorry. Should get another coffee I guess :+1:
