### ISSUE TITLE
在 router 中配置了 fallback: false 后，在 IE 9 下不停的刷新

### ISSUE THREAD

**Issue by cheneywan** [vuejs/vue-hackernews-2.0#221]
测试环境中只把 vue-router 版本升级到 2.7.0，其他代码都没改

本希望通过 fallback 选项把自动回滚到 hash 模式给禁用掉，从而实现在 IE 9 中点击链接能重新刷新页面。不知道是不是配置有问题？

![image](https://user-images.githubusercontent.com/2441562/27824476-2f8959ec-60df-11e7-96d0-a042baf94115.png)

**Comment by cheneywan** [comment]
@JounQin

**Comment by JounQin** [comment]
把 `fallback: false` 去掉也是一样的，#218 ，具体原因没深入看

我自己的 [vue-ssr](https://github.com/JounQin/vue-ssr) 在 IE 9 上运行是没有问题的。

https://vue-ssr.1stg.me/

**Comment by cheneywan** [comment]
@JounQin 多谢回复，您的 Demo 确实没问题

我看了下，大概是在执行 `store.replaceState(window.__INITIAL_STATE__)` 这句后就 reload 了，具体原因没看出来 ଲ 

![untitled2](https://user-images.githubusercontent.com/2441562/27846692-c8fc6b6e-616b-11e7-8187-846fe8d1c6e0.gif)

**Comment by wenyejie** [comment]
我也遇到过类似的问题, 不过我是直接在safari(也好像是QQ浏览器, 有点记不得了),
不过我当时, 是使用store的时候, 好像出现了某种类似于死循环的bug(好像是, actioin与getters之间出了点问题), 具体问题没查出来,
毕竟一直在reload, 后来我重构了一遍该方法就好了!

**Comment by xsbchen** [comment]
暴力解决：
```javascript
if (!(window.history && 'pushState' in window.history)) {
  // 阻止调用store.replaceState，导致死循环的关键
  window.__INITIAL_STATE__ = null;

  // 直接跳转
  window.history.pushState = function(state, title, url) {
    location.href = url;
  };

  // 直接跳转
  window.history.replaceState = function(state, title, url) {
    location.href = url;
  };
}
```
