### ISSUE TITLE
打包之后没有index.jtml

### ISSUE THREAD

**Issue by jsgr** [vuejs/vue-hackernews-2.0#222]
请问打包之后没有index.html,这样要怎么部署到服务器

**Comment by JounQin** [comment]
> HackerNews clone built with Vue 2.0 + vue-router + vuex, with server-side rendering.

这个项目是服务器端渲染的，不需要 *index.html* ，当然服务器端渲染的时候也是有模版的，`src/index.template.html`，详见 https://github.com/vuejs/vue-hackernews-2.0/blob/master/server.js#L18

**Comment by jsgr** [comment]
谢谢，看到 src/index.template.html 文件里的内容了。可是在服务器上 npm start 之后并不能运行。请问应该怎么操作？

**Comment by JounQin** [comment]
先 build 再 start，自己看逻辑啊，有问题去论坛问。

**Comment by jsgr** [comment]
好的，谢谢。
