### ISSUE TITLE
Scoped styles not working on SSR

### ISSUE THREAD

**Issue by eugenioclrc** [vuejs/vue-hackernews-2.0#229]
If you got a 
`<style scoped> h1 { color: red!important; }</style>`

You wont see the h1 in red when loading from server, insted if you load the page throught the router you will see the h1 red.

**Comment by LinusBorg** [comment]
all component styles in this app are scoped and work well nonetheless, so this would be odd.

Is it the `!important`?

**Comment by eugenioclrc** [comment]
In this example its only one place where you use scoped style, but in a real world example you will see it. I think this issue should be move to the main vue repo. It started to happen me in the last vue version.

**Comment by valentinvieriu** [comment]
I subscribe to the same situation. After upgrading to 2.4.0 scopes style stoped working. I'm not sure if it's a ssr or a vue in general.

**Comment by eugenioclrc** [comment]
open issue in vue, and close this
https://github.com/vuejs/vue/issues/6128
