### ISSUE TITLE
How to render the initial page html rather than just initial state?

### ISSUE THREAD

**Issue by oliverzy** [vuejs/vue-hackernews-2.0#23]
Hi, the demo is so cool. I'm just very interested in how the ssr improve the initial page load experience.

The question I have is in this demo, it seems on the server, an INITIAL STATE will be generated and sent to client, and then the client js will render the page based on that state.

What I expect is the server will render all the html and send them to the client.

Could you explain how to do this in vue server rendering?

Thanks

**Comment by yyx990803** [comment]
That's not what's happening... The initial markup is rendered together with the state. The state is needed for the client to "pick up" the already rendered HTML.
