### ISSUE TITLE
Repeat reject/resolve promise in src/entry.server.js

### ISSUE THREAD

**Issue by hstarorg** [vuejs/vue-hackernews-2.0#231]
Code Link: [https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/entry-server.js#L19-L48](https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/entry-server.js#L19-L48)

**Comment by LinusBorg** [comment]
Is this a question? If so, what is the question?

Or do you think you have spotted a mistake?

I don't understand your intention, sorry.

**Comment by hstarorg** [comment]
This is not the better grammar.
If some promise resolved or rejected, we should return the promise.
Or not , the code will be runing after promise resolved  or rejected.

**Comment by xqin** [comment]
when i request `http://127.0.0.1:8080/helloworld`,

![image](https://user-images.githubusercontent.com/1265888/28821652-df517c32-76e8-11e7-9238-5fb9c80f30c0.png)
https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/entry-server.js#L29-L31

this code will be reject the `Promise`, and return to this position 
![image](https://user-images.githubusercontent.com/1265888/28821709-14f29f60-76e9-11e7-9666-a0c3631d38d8.png)
https://github.com/vuejs/vue/blob/dev/packages/vue-server-renderer/build.js#L7952-L7953

there is no need to let code continue running to `Promise.all`.
![image](https://user-images.githubusercontent.com/1265888/28821744-3c40aec2-76e9-11e7-8b15-00b6f84db8c6.png)
https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/entry-server.js#L36-L49

so i suggest add `return` in this position, like this.
![image](https://user-images.githubusercontent.com/1265888/28821898-d0312260-76e9-11e7-9834-0c28ab4f8f56.png)

There is also the same problem here
![image](https://user-images.githubusercontent.com/1265888/28822409-c389f120-76eb-11e7-962a-efb4ecf75b3c.png)
https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/entry-server.js#L18-L20

**Comment by sirlancelot** [comment]
I could be wrong here, but I think the issue that @hstarorg is trying to point out is that the two `reject()` lines don't `return`, causing execution to continue even after the promise is rejected.

**Comment by hstarorg** [comment]
@sirlancelot Yes, the logic will be run after project rejected/resolved.
@xqin and me means same question.
