### ISSUE TITLE
求一个不用ssr的热更新的例子

### ISSUE THREAD

**Issue by SteveCruise** [vuejs/vue-hackernews-2.0#234]
不用ssr，但是也不用webpack-dev-server命令，因为webpack-dev-server命令定制化不行。
而是像这个例子一样用两个库：webpack-dev-middleware和webpack-hot-middleware的vue热更新项目。

**Comment by AfterThreeYears** [comment]
https://github.com/AfterThreeYears/vue_client_template_gayhub

**Comment by SteveCruise** [comment]
@AfterThreeYears 你这个还是用了webpack-dev-server

**Comment by SteveCruise** [comment]
那个我在lavas的demo里找到一个不用ssr又不用webpack-dev-server命令的热重载例子，是和express搭配的，自己成功也改成了和koa2搭配，但是好大一坨乱七八糟的webpack配置，受不了了放弃了。
