### ISSUE TITLE
How to get .txt file?

### ISSUE THREAD

**Issue by wenyejie** [vuejs/vue-hackernews-2.0#236]
Hi, i have trouble in vue ssr, i want to get .txt! But failed!
Return to 404 | not page? how to get .txt successfully?
example: `http://www.example/robot.txt` or `http://www.example/sitemap.xml`

**Comment by john-ko** [comment]
I believe you can just add those files to the `public/` folder

**Comment by wenyejie** [comment]
> I believe you can just add those files to the public/ folder
@john-ko , yes! you are right! thx u!
