### ISSUE TITLE
How do I disable JavaScript prefetch?

### ISSUE THREAD

**Issue by wenyejie** [vuejs/vue-hackernews-2.0#238]
Hi, There is too much prefetch in the project, hoping to disable this function?
Now, what should I do!!! please help!!! thx!

**Comment by valentinvieriu** [comment]
What do you mean by prefetch? The service worker downloading things in the background?
If yes, just disable the service worker.

https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/entry-client.js#L67

**Comment by daliborgogic** [comment]
[Manual Asset Injection](https://ssr.vuejs.org/en/build-config.html#manual-asset-injection)

```html
<html>
  <head>
    <!-- use triple mustache for non-HTML-escaped interpolation -->
    {{{ renderResourceHints() }}}
    {{{ renderStyles() }}}
  </head>
  <body>
    <!--vue-ssr-outlet-->
    {{{ renderState() }}}
    {{{ renderScripts() }}}
  </body>
</html>
```

**Comment by wenyejie** [comment]
@valentinvieriu , @daliborgogic 
thank for your help! 
question has been solved!!
