### ISSUE TITLE
关于vue-router的history模式

### ISSUE THREAD

**Issue by wu67** [vuejs/vue-hackernews-2.0#242]
[vue-router的文档](https://router.vuejs.org/en/essentials/history-mode.html#nodejs-express)不是说history模式（node环境）要配置后台、建议使用[connect-history-api-fallback](https://github.com/bripkens/connect-history-api-fallback)么？但是hackernews里面并没有使用到这个呀，请问这是什么原理呢？

**Comment by lincenying** [comment]
https://github.com/vuejs/vue-hackernews-2.0/blob/master/server.js#L129

**Comment by rocketxujia** [comment]
vue-router的文档说history模式是指针对SPA模式下的，所以说的是作为静态资源的服务器的配置，用node举例也是作为静态应用服务来说的。 但 vue-hackernews-2.0 项目作为SSR本身是都会对每个页面路由作渲染处理的啊。
