### ISSUE TITLE
redirect to many

### ISSUE THREAD

**Issue by falstack** [vuejs/vue-hackernews-2.0#251]
1：clone this repo
2：npm install & npm run dev
3：use chrome open localhost:8080
4：ERR_TOO_MANY_REDIRECTS

**Comment by shhdgit** [comment]
You can resolve this err by comment three line code in entry-server.js:18

```
export default context => {
  return new Promise((resolve, reject) => {
    const s = isDev && Date.now()
    const { app, router, store } = createApp()

    const { url } = context
    const fullPath = router.resolve(url).route.fullPath

    // if (fullPath !== url) {
    //   reject({ url: fullPath })
    // }
```

**Comment by JounQin** [comment]
@shhdgit This is is related to `route-cache` rather than redirecting on server and which can be fixed like following as https://github.com/vuejs/vue-hackernews-2.0/pull/253:
``` js
// server.js

// app.use(microcache.cacheSeconds(1, () => useMicroCache))
app.use(microcache.cacheSeconds(1, req => useMicroCache && req.originalUrl))
```

**Comment by shhdgit** [comment]
@JounQin gotcha, thank you!
