### ISSUE TITLE
webpack-dev-middleware instead of webpack-dev-server

### ISSUE THREAD

**Issue by sunabozu** [vuejs/vue-hackernews-2.0#26]
Is there a particular reason why you're using your own express server based on `webpack-dev-middleware` instead of just using `webpack-dev-server`? I've tried both, and it seems like there is no difference (both support hot reload and all the features I know of), but in your case it's much more complicated and obscure, especially when you need to change something in your build process.

So if it's all the same, I suggest to replace that server with a simple `webpack-dev-server --inline --hot` command in the `package.json`. For people who try to use hot real for the first time it would be much clearer and simpler.

**Comment by yyx990803** [comment]
Because we need to

1. Do server-side rendering with custom handlers
2. Watch and rebuild both the server bundle AND the client bundle
3. `webpack-hot-middleware` has better error display when compilation fails.
