### ISSUE TITLE
How to debug the server bundle?

### ISSUE THREAD

**Issue by oliverzy** [vuejs/vue-hackernews-2.0#27]
I'm playing with the demo for past three days and get a rough understanding of how the whole system run. I would say vue 2.0 is amazing. I want to upgrade my 1.x to 2.x ASAP.

The only issue that block me is for server bundle debugging.
I basically fail to debug the server bundle and have no idea how to setup breakpoint for the Vue app. I can break in the server.js anyway, but it's not that useful because I would like to debug my Vue app.
And debugger statement doesn't work either.

Please suggest. Currently I have to fallback to use console.log.

**Comment by yyx990803** [comment]
This is something that still needs to be improved in `bundleRenderer`.

**Comment by sotaan** [comment]
I think that one cool and missing functionality in Vuex shall be the ability to replay all your actions and mutations inside your SPA from a single log file.
There is a React example i can show you as reference: [https://github.com/dtschust/redux-bug-reporter](redux-bug-reporter)
