### ISSUE TITLE
Changes to index.template.html do not initiate hot module replacement

### ISSUE THREAD

**Issue by diff-dennis** [vuejs/vue-hackernews-2.0#286]
When changing the `index.template.html` file, the changes don't get reflected in the browser view.
The console logs `index.html template updated.` but somehow the HMR runtime does nothing.

**Comment by jacoborus** [comment]
HMR doesn't handle the change of `index.template.html` you'll have to refresh the page in your browser

**Comment by diff-dennis** [comment]
Understood, thanks!
