### ISSUE TITLE
你好，项目运行异常

### ISSUE THREAD

**Issue by suhanyujie** [vuejs/vue-hackernews-2.0#29]
你好，前辈~
我将这个仓库给clone下来了。按照步骤 npm install->npm run dev
提示报错了：
![image](https://cloud.githubusercontent.com/assets/8400113/18654552/b2ad74fa-7f14-11e6-937f-61861050fadd.png)

我的node环境是6.6的
webpack也全局安装了。

谢谢！

**Comment by transtone** [comment]
一样，不知哪里的问题。

**Comment by yyx990803** [comment]
fixed in 958e49536e204961aaeaf95b2dbf334ccbc204b6

**Comment by suhanyujie** [comment]
thanks for your answer~
I found the solution here [https://github.com/angular/angular-cli/issues/2234](url)

> 
>Thanks @colindevs - anyone using Laravel (laravel-elixir-webpack-official) just do:
>
>npm uninstall webpack --save-dev
>
>followed by
>
>npm install webpack@2.1.0-beta.22 --save-dev
>
>Then you should be able to gulp again. Fixed the issue for me.
