### ISSUE TITLE
how to uglify ssr response body?

### ISSUE THREAD

**Issue by falstack** [vuejs/vue-hackernews-2.0#295]
这是我的 SSR 网站：http://calibur.tv/

它工作的很出色，我非常高兴，但是有一个问题我一直不知道该如何解决：

我们观察这个页面的source：view-source:https://www.calibur.tv/bangumi/1
发现它的 body 并不是 uglify 的，当然我在 webpack config 里是配置了 UglifyJs 的：
https://github.com/calibur-tv/Avalon/blob/master/build/webpack.base.config.js#L129

我不知道该用 Vue SSR 来解决这个问题还是 Node.js 或是 Nginx，有什么建议吗？

**Comment by JounQin** [comment]
css-loader 没开启 minimize 吧

**Comment by falstack** [comment]
这不是一个编译时问题，因为编译时是 OK的，minisize 的，但是运行时的 css 不是

也就是说，即使我这样做也是没用的：
```
use: isDev
  ? ['vue-style-loader', 'css-loader?importLoaders=2', 'postcss-loader', 'sass-loader']
  : ExtractTextPlugin.extract({
      fallback: 'vue-style-loader',
      use: ['css-loader?minimize?importLoaders=2', 'postcss-loader', 'sass-loader']
    })
```

**Comment by JounQin** [comment]
vue-loader 里的 scss 配置 css-loader 和 .scss 单独配置无关
https://github.com/calibur-tv/Avalon/blob/master/build/webpack.base.config.js#L50

**Comment by falstack** [comment]
@JounQin 你好，刚才我确认了一下，的确是 vue-loader 里的 css-loader 也需要配置，并且我也已经找到了根本原因，解决方案是这样的：

```
// vue-loader 中的 css-loader 这样配置
{
  loader: 'css-loader',
    options: isDev ? {} : {
      minimize: true
    }
}
// css 中的 loader 这样配置
{
  test: /\.(scss|css)$/,
    use: isDev
  ? ['vue-style-loader', 'css-loader', 'sass-loader']
  : ExtractTextPlugin.extract({
    fallback: 'vue-style-loader',
    use: [{
      loader: 'css-loader',
      options: {
        minimize: true,
        importLoaders: 2
      }
    }, 'postcss-loader', 'sass-loader']
  })
},
```
