### ISSUE TITLE
Deploy on Netlify

### ISSUE THREAD

**Issue by Oscarteg** [vuejs/vue-hackernews-2.0#297]
I'm trying to figure out how to deploy on Netlify. When I build the project with `npm run build` it creates the `dist/` folder. 

But on Netlify I need to set a deploy command and publish directory. I set the publish directory to `dist/` but the website isn't available. Is it necessary to run a node server?

**Comment by tracker1** [comment]
You need to build on a system with node... I know nothing about netlify, or how you're configured... you may need to commit your dist/ folder to the master branch?
