### ISSUE TITLE
添加alias目录别名无效

### ISSUE THREAD

**Issue by 516458780** [vuejs/vue-hackernews-2.0#304]
在webpack.server.config.js中添加了
`
    resolve: {
        alias: {
            'middleware': path.resolve(__dirname, '../server/middleware'),
        }
    },`

然后在server.js中使用
`let bodyParser = require('middleware/bodyParser.js');`

运行run dev会提示错误
![image](https://user-images.githubusercontent.com/23350816/38075921-941d5d9a-3366-11e8-9ee2-9b213b102273.png)

**Comment by JounQin** [comment]
webpack.server.config.js 跟 server.js 无关，它是用来打包 entry.server.js 的，提问题前至少了解下程序是怎么运行的吧，server.js 是直接运行 `node server.js` 的，怎么能跟 webpack 扯上关系。

**Comment by 516458780** [comment]
@JounQin 不好意思，刚学没多久，求大神指教一下这个是什么原因

**Comment by JounQin** [comment]
……我已经说得很清楚了，运行 server.js 并不走 webpack，alias 当然没用，请关闭 issue，有问题去论坛。

**Comment by 516458780** [comment]
@JounQin 不好意思，再问一下，如果我希望在开发环境中也能使用alias，那我需要怎么配置？因为现在运行node server.js的时候client部分的path是有被alias正常替换的，而server部分却没有，但是我看了webpack的文档也没看懂是什么原因
