### ISSUE TITLE
如何才能使autoprefixer正常工作

### ISSUE THREAD

**Issue by wenyejie** [vuejs/vue-hackernews-2.0#309]
我clone了一份vue-hackernews-2.0, 想写一份demo, 但是, 配置了相关autoprefixer的配置, 但是没有得到正确的结果, 请问该如何配置才是正确的?

- .postcssrc.js?
- postcss.config.js?

懵逼中....

**Comment by JounQin** [comment]
至少提供复现吧。。。

**Comment by wenyejie** [comment]
@JounQin 
好的, 我install了postcss-loader,
进行了如下配置
```js
// postcss.config.js
module.exports = {
  plugins: [
    require('autoprefixer')({browsers: ['last 5 versions', 'Android >= 4.0', 'ios >= 8.0']})
  ]
};
```
但是没生效

**Comment by wenyejie** [comment]
@JounQin 
sry, 对webpack配置, 我也不是特别懂!
我也试着加了, 但是不知道, 我哪里出了问题! 失败了
[https://github.com/wenyejie/vue-hackernews-2.0](https://github.com/wenyejie/vue-hackernews-2.0)
麻烦帮我看看, thx

**Comment by JounQin** [comment]
https://github.com/wenyejie/vue-hackernews-2.0/blob/master/build/webpack.base.config.js#L48-L62
你压根儿没把 postcss-loader 加进去啊，这种问题到论坛问就好了，issue 是报 bug 的。
