### ISSUE TITLE
使用第三方UI库出错

### ISSUE THREAD

**Issue by freemember007** [vuejs/vue-hackernews-2.0#31]
在client-entry.js中导入后在view中使用UI库中的元件，不报错，但也没效果：
import Mint from 'mint-ui';
import 'mint-ui/lib/style.css';
Vue.use(Mint);

如果直接在view中导入UI库或UI库中的具体元件，则会报错：
document或window未创建

**Comment by yyx990803** [comment]
这是第三方库的问题。要使用 ssr，引入的库必须能够在 node 下运行。

**Comment by freemember007** [comment]
哦。了解了。谢谢！
