### ISSUE TITLE
vue 内存溢出

### ISSUE THREAD

**Issue by PLDaily** [vuejs/vue-hackernews-2.0#310]
英文不好，只能中文描述了。vue做服务端渲染时，因为前后端都需要获取到数据，所以将数据存放在vuex的state中，当每次访问不同的页面时，每个页面的数据都会存在vuex的state中，然后就内存溢出了。以下是用heapdump打印的快照，第一个heapdump为服务刚开启时，第二个heapdump是访问几次页面后

![2018-04-13 3 49 05](https://user-images.githubusercontent.com/11615211/38723043-7406e6d4-3f32-11e8-805c-edb4727dddb6.png)

**Comment by main2017** [comment]
@PLDaily 请问你配置好了吗，我跟着官方文档配置，打包报错

**Comment by main2017** [comment]
@PLDaily 方便的话留个Q互相学习

**Comment by PLDaily** [comment]
这个问题是由于每次访问页面时都将数据通过{key: value}的形式存到store中，每次访问不同的页面store中就会新增一条数据，导致最后store中数据过大加载缓慢。只要每次访问页面，把数据存到同一个key下即可。
