### ISSUE TITLE
参考这个 简单 写了一个脚手架，同时支持SSR SPA

### ISSUE THREAD

**Issue by sailei1** [vuejs/vue-hackernews-2.0#317]
参考这个 简单 写了一个脚手架，同时支持SSR SPA，请求方式一定要用vuex ,简单测试了一下可以
https://github.com/sailei1/vue-ssr
@yyx990803

**Comment by sailei1** [comment]
https://github.com/sailei1/vue-ssr-template

**Comment by JounQin** [comment]
……这个 issue 放在这里的意义是什么？推广吗？这种 SSR 模板很多，建议关闭 issue

**Comment by sailei1** [comment]
不是推广，关闭吧
