### ISSUE TITLE
服务端直出页面需要等到css文件下载完毕才能正确渲染

### ISSUE THREAD

**Issue by freemember007** [vuejs/vue-hackernews-2.0#32]
在服务端渲染的情况下，可以直接用到的样式放在html里吗？直接由服务端输出，这样会更快啊？

**Comment by yyx990803** [comment]
可以啊... 生产模式下把生成的 css 在启动服务器的时候读到内存里。

**Comment by freemember007** [comment]
谢谢谢谢！"使用第三方UI库出错" 的问题能否解答一下呢？
