### ISSUE TITLE
低版本的安卓 vue2.0挂载不成功出现白页 如何处理呢 

### ISSUE THREAD

**Issue by zhangli254804018** [vuejs/vue-hackernews-2.0#33]
http://app.52tt.com/active/promotion_lottery_mudule/index.html?gid=295808&uid=5717516&version=34078722&os_type=1&platform=1&app=0
该页面采用vue2.0 
  "es6-promise": "^3.2.1",
    "vue": "^2.0.0-rc.1",
    "vue-server-renderer": "^2.0.0-rc.1",
    "vuex": "^2.0.0-rc.4"
测试环境:三星note2 海马玩模拟器 夜神模拟器安卓 都不行 请问如何解决？

**Comment by zhangli254804018** [comment]
vuex2.0的bug

**Comment by yyx990803** [comment]
1. 请到对应的仓库开 issue
2. 我没有这些旧浏览器，请想办法提供页面上的报错信息。

**Comment by ymma** [comment]
目测应该是 promise对低版本Android的本地浏览器支持不好；

http://caniuse.com/#search=Promise

**Comment by zhangli254804018** [comment]
项目暂时移除了vuex2.0就好了 vuex2.0 bate版本问题 
    "es6-promise": "^3.2.1",
    "vue": "^2.0.0-rc.1",
    "vue-server-renderer": "^2.0.0-rc.1",
    "vuex": "^1.0.0-rc.2"
目前使用vue2.0 配置vuex 1.0就没啥问题

**Comment by zhangli254804018** [comment]
通过小伙伴的回馈发现根本的在于 vuex2 还是 es6/7语法 
最好是选择针对的es6-promise 依赖包 之前遇到的问题也是这个所困扰。

**Comment by nokelong** [comment]
现在遇到个问题，使用axios返回的promise乱了，导致华为mate 9 自带的4.0浏览器出现空白。其他浏览器Ok了

**Comment by toassassin** [comment]
@yyx990803 你好，vue2.0在华为自带浏览打开白屏又解决方案了吗，网上查到的babel-profill、es6-promise等es6转es2015的方案都没能解决

**Comment by sg552** [comment]
来这里看: http://siwei.me/blog/posts/vuejs-huawei
 
基本原因是由于 es6 在 一些低版本手机浏览器中不支持造成的. 华为的机器据说用的是低版本浏览器, 所以也不行. 

解决办法是: 
1. node 的版本不能低. 我用的是 10.8.0   ( 5.x 不行)
2. 使用  babel-polyfill
3. 重新打包即可. 具体过程见上面的链接.
