### ISSUE TITLE
项目正常跑起来了，但是页面打不开

### ISSUE THREAD

**Issue by FE-xiaoJiang** [vuejs/vue-hackernews-2.0#333]
开发环境，应该是renderer.renderToString这一句执行出问题了，估计createRender生成就有问题，下面的console都没有打印
renderer.renderToString(context, (err, html) => {
    console.log('html==>', html)
    if (err) {
      return handleError(err)
    }
    console.log('html==>', html)
    res.send(html)
    if (!isProd) {
      console.log(`whole request: ${Date.now() - s}ms`)
    }
  })

**Comment by anneincoding** [comment]
@FE-xiaoJiang   请问您的项目想在好了吗？我遇到了同样的问题，我是生产环境打不开页面

**Comment by gyfeng1003** [comment]
@FE-xiaoJiang 请问怎么解决页面打不开的

**Comment by liangyuhong160** [comment]
我也是，这个是不是又问题，只传了context，没有传vue的实例 啊，官网的代码不是这样的吗，renderer.renderToString(app, context, (err, html) => {
  // 页面 title 将会是 "Hello"
  // meta 标签也会注入
})，可demo也是官网的，我不能怀疑他有问题。。。

**Comment by bobohuochai** [comment]
@lyhzwf  获取异步数据的时候网络不通，https://hacker-news.firebaseio.com/ 这个网址访问不了。所以一直pending。

**Comment by iiimix** [comment]
> @lyhzwf 获取异步数据的时候网络不通，https://hacker-news.firebaseio.com/ 这个网址访问不了。所以一直pending。

我debugger到了createAPI函数，才发现的，但不知道为什么这个issue是closed
