### ISSUE TITLE
What's the best way to integrate Sentry

### ISSUE THREAD

**Issue by shreyas-a** [vuejs/vue-hackernews-2.0#334]

**Comment by akanshgulati** [comment]
@shreyas-a  have you tried using Sentry Plugin for Vue?https://docs.sentry.io/clients/javascript/integrations/vue/

**Comment by shreyas-a** [comment]
I've put `Raven.config('URL').addPlugin(RavenVue, Vue).install()` in `entry-client.js`, works fine!
