### ISSUE TITLE
Routing does not work

### ISSUE THREAD

**Issue by SkipTyler** [vuejs/vue-hackernews-2.0#358]
Hey.
I took this configuration for learning ssr

I didn’t do a lot for myself, and after <router-link> stopped working

Works if the link leads to the root component.

The same problem with browser buttons "forward" and "back"

Url is changing, but the content on the page is not.

Where did I make a mistake?

There is a [repo](https://gitlab.com/SkipTyler/vue-ssr-skiptyler.git).

**UPD**
If I remove `asyncData()` from the `src/views/posts.vue` component, then the routing works.

**Comment by didagu** [comment]
The link to the repo is invalid
