### ISSUE TITLE
https://vue-hn.herokuapp.com/ is down

### ISSUE THREAD

**Issue by sunjie21** [vuejs/vue-hackernews-2.0#420]
Live Demo has been down for several days, can anyone fix it?

**Comment by mbana** [comment]
<https://vue-hn.herokuapp.com/>

Still looks down to me:

![image](https://user-images.githubusercontent.com/22658/224663257-398290b2-3efb-41e6-9578-26c320a38527.png)

> Application error
> An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
> `heroku logs --tail`

Why did you close this @sunjie21.
