### ISSUE TITLE
npm run dev出错

### ISSUE THREAD

**Issue by jacklidesign** [vuejs/vue-hackernews-2.0#43]
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! vue-hackernews-2.0@ dev: `node server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-hackernews-2.0@ dev script 'node server'.
npm ERR! This is most likely a problem with the vue-hackernews-2.0 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-hackernews-2.0
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls vue-hackernews-2.0
npm ERR! There is likely additional logging output above.

**Comment by yyx990803** [comment]
The README says: **Requires Node.js 6+**
