### ISSUE TITLE
跑不起来,老是报错.少了这个文件也没看到呀???

### ISSUE THREAD

**Issue by timy-life** [vuejs/vue-hackernews-2.0#44]
> vue-hackernews-2.0@ dev /work/code/TestProject/vue-hackernews-2.0
> node server

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/work/code/TestProject/vue-hackernews-2.0/dist/server-bundle.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/work/code/TestProject/vue-hackernews-2.0/server.js:33:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! vue-hackernews-2.0@ dev: `node server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-hackernews-2.0@ dev script 'node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-hackernews-2.0 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-hackernews-2.0
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-hackernews-2.0
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /work/code/TestProject/vue-hackernews-2.0/npm-debug.log

**Comment by artkynet** [comment]
@timy-life try $ sudo npm run dev

**Comment by yyx990803** [comment]
请确保你的 npm 依赖正确安装...
