### ISSUE TITLE
How include <script> tag in template component ?

### ISSUE THREAD

**Issue by tronghiep92** [vuejs/vue-hackernews-2.0#46]
Hi guys,

I want to include scipts only in page Contact.vue

<template>
 <div id="map"></div>
 <script
    src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY">
 </script>
</template>
With mode developer it work, but in production it not working and removed <script>?

Please help me?
Tks!!

**Comment by yyx990803** [comment]
This is not the right repo to ask this question.
