### ISSUE TITLE
一运行npm run dev就报错,信息如下

### ISSUE THREAD

**Issue by qxl1231** [vuejs/vue-hackernews-2.0#5]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-hackernews-2.0@~predev: vue-hackernews-2.0@
6 silly lifecycle vue-hackernews-2.0@~predev: no script for predev, continuing
7 info lifecycle vue-hackernews-2.0@~dev: vue-hackernews-2.0@
8 verbose lifecycle vue-hackernews-2.0@~dev: unsafe-perm in lifecycle true
9 verbose lifecycle vue-hackernews-2.0@~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Ivyjohnson/Downloads/vue-hackernews-2.0-master/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin
10 verbose lifecycle vue-hackernews-2.0@~dev: CWD: /Users/Ivyjohnson/Downloads/vue-hackernews-2.0-master
11 silly lifecycle vue-hackernews-2.0@~dev: Args: [ '-c', 'node server' ]
12 silly lifecycle vue-hackernews-2.0@~dev: Returned: code: 1  signal: null
13 info lifecycle vue-hackernews-2.0@~dev: Failed to exec dev script
14 verbose stack Error: vue-hackernews-2.0@ dev: `node server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid vue-hackernews-2.0@
16 verbose cwd /Users/Ivyjohnson/Downloads/vue-hackernews-2.0-master
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v6.2.2
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error vue-hackernews-2.0@ dev: `node server`
22 error Exit status 1
23 error Failed at the vue-hackernews-2.0@ dev script 'node server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vue-hackernews-2.0 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vue-hackernews-2.0
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vue-hackernews-2.0
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by yyx990803** [comment]
这个 log 看不出来哪里有问题，js 本身的 error stack 呢？

**Comment by qxl1231** [comment]
我今天一运行,又可以了..奇怪,可能是之前node版本没有升到6+导致的

**Comment by haycco** [comment]
8080端口被占用了的原因
