### ISSUE TITLE
I just don't know how is the vue instance append to the document.body?

### ISSUE THREAD

**Issue by pengfu** [vuejs/vue-hackernews-2.0#50]
In client-entry.js , we have 
`// actually mount to DOM`
`app.$mount('#app')`
I am puzzled with how is the instance append to the body? Can anybody give an advice?

**Comment by LinusBorg** [comment]
I'm not sure I understand what you are asking? Are you asking how `$mount()` is working?

Well if the [documentation for $mount](http://vuejs.org/api/#vm-mount) is not enough, feel free to reas the source and ask a more specific question.

**Comment by pengfu** [comment]
I'm sorry,in my understanding , what `app.$mount('#app') ` do is just mount the Vue instance to the #app selector , in the case here is the div element . What I don't understand is which code shows how the div element mount to the document.body.  Didn't it need code like `app.$appendTo(document.body)`?
![image](https://cloud.githubusercontent.com/assets/7261281/19559061/7cae670c-9700-11e6-859d-b59cf990eade.png)

**Comment by clanstyles** [comment]
I'm also confused how Vue is binding to the DOM.

I also can't get v-model to bind unless I change it to a <div id="app"></div> and actually bind it. What's going on here? I've asked in Gitter.

**Comment by pengfu** [comment]
@yyx990803 Could you please give some advice?

**Comment by pengfu** [comment]
Thanks to @LinusBorg ,
to latter readers ,refer to the url below for more information.
[http://forum.vuejs.org/t/vue-hackernews-2-0-i-just-dont-know-how-is-the-vue-instance-append-to-the-document-body/1844](url)
