### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by vfreitas-** [vuejs/vue-hackernews-2.0#52]
Hi guys! 

I'm trying to add TweeMax.js from GSAP on a project with the same SSR and webpack configuration as this one ( I did copy everything for testing purposes ). When I run `npm run dev` it generates de client and vendor bundles perfectly, but when I access any route it throws the following exception:

```
/Users/vitor/Sites/ssr-test/front-end/server.js:105
        throw err
        ^

ReferenceError: document is not defined
    at Function.<anonymous> (/Users/vitor/Sites/ssr-test/front-end/node_modules/gsap/src/uncompressed/TweenMax.js:2571:11)
    at check (/Users/vitor/Sites/ssr-test/front-end/node_modules/gsap/src/uncompressed/TweenMax.js:5986:61)
    at new Definition (/Users/vitor/Sites/ssr-test/front-end/node_modules/gsap/src/uncompressed/TweenMax.js:6010:10)
    at window._gsDefine (/Users/vitor/Sites/ssr-test/front-end/node_modules/gsap/src/uncompressed/TweenMax.js:6015:12)
    at Array.<anonymous> (/Users/vitor/Sites/ssr-test/front-end/node_modules/gsap/src/uncompressed/TweenMax.js:2524:11)
    at /Users/vitor/Sites/ssr-test/front-end/node_modules/gsap/src/uncompressed/TweenMax.js:7791:9
    at Object.<anonymous> (/Users/vitor/Sites/ssr-test/front-end/node_modules/gsap/src/uncompressed/TweenMax.js:7802:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

I did some research, and I think it's because we don't have document or window global objects on the server side environment. I tried to fix it declaring both as global variables on the `server-entry.js` file, but it was unsuccessful 

```
if (typeof(window) == 'undefined'){
    let dummyElement = { style: {}, getElementsByTagName: function() { return [] } }
    global.window = {}
    global.navigator = { userAgent: "" }
    global.document = { createElement: function() { return dummyElement } }
}
```

Maybe anyone can help me with that? I'm probably missing something.

Thanks!

**Comment by vfreitas-** [comment]
I'm not sure if it's the better way to do this, but I've resolved this issue using the [jsdom](https://github.com/tmpvar/jsdom) module to fake the browser objects. 

on the top of server.js file I included these lines
```
const jsdom     = require('jsdom').jsdom
//...
global.document = jsdom('<!doctype html><html><body></body></html>', { url: 'http://localhost' })
global.window   = document.defaultView
global.navigator = window.navigator
```

Maybe this can help someone in the future :)

**Comment by stephenzhao** [comment]
@vfreitas im tring to fix the err by using ur way. but still not work ,
put the code
```
global.document = jsdom('<!doctype html><html><body></body></html>', { url: 'http://localhost' });
  global.window   = document.defaultView;
  global.location = window.location;
  global.navigator = window.navigator;
```
into the server.js , still throw the error [ReferenceError: window is not defined] , god pls help..

**Comment by ktquez** [comment]
Working for me.
```
require('jsdom-global')(html, {
  url: `http://${process.env.HOST}:${process.env.PORT}`
})
```

**Comment by stephenzhao** [comment]
odd... when console.log(window) ,it could be printing the object of window, but still not work.and when i push the `global.window = {}, `, it just throw another the error "Cannot read property 'userAgent' of undefined "etc..
i guess the the node runtime has found `window `.but why it's can not be found when `global.window = document.defaultView`?
 so what should i do.

**Comment by tronghiep92** [comment]
Try install in `client-entry.js`
```
import Vue from 'vue';
import VueResource from 'vue-resource';
Vue.use(VueResource);
```

**Comment by mib200** [comment]
@tronghiep92 This will just include it in the vendor.js file. But it doesn't make it available in global window object on the client side.

**Comment by miyalee** [comment]
[jsdom](https://github.com/tmpvar/jsdom) (version 11.0.0)is working for me:
in server.js:
```
const { JSDOM } = require('jsdom')
...
const dom = new JSDOM('<!doctype html><html><body></body></html>', { url: 'http://localhost' })
global.window = dom.window
global.document = window.document
global.navigator = window.navigator
```
