### ISSUE TITLE
How to add new css from node module

### ISSUE THREAD

**Issue by mimani-s** [vuejs/vue-hackernews-2.0#58]
Hi,

I was trying to enhance this, I wanted to use [flexboxgrid](http://flexboxgrid.com/) with this. I added it in package.json and installed it. I was trying to include this in `index.html` like this:

```
<link rel="stylesheet" href="/./node_modules/flexboxgrid/dist/flexboxgrid.min.css" type="text/css" >
```

But I am getting following error in the browser:

```
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:8080/node_modules/flexboxgrid/dist/flexboxgrid.min.css".
```

I am not sure what I should be right way to do this this, what am I doing wring, Please help.

**Comment by yyx990803** [comment]
You are linking into `node_modules` which is not served by the server. Only files in `dist` are served .
