### ISSUE TITLE
How to structure this project to enable lazy-loading routes...

### ISSUE THREAD

**Issue by declandewet** [vuejs/vue-hackernews-2.0#59]
...but still have them be server-render compatible?

I've tried to code this in for around 2 weeks - hopefully someone knows a solution, because my brain is starting to hurt :smile:

I have ready a smaller [example repo](https://github.com/declandewet/vue2-ssr-lazy-error) demonstrating my issue.

For more context, refer to this [StackOverflow question](http://stackoverflow.com/questions/40295201/how-to-structure-a-vue-2-0-app-for-server-rendered-lazy-routes).

I'd really like to see a method of accomplishing this documented in `vue-router` - which I'm more than happy to do, as long as I'm pointed in the right direction :smile:

**Comment by declandewet** [comment]
This might be a duplicate of #17

**Comment by yyx990803** [comment]
Closing as duplicate
