### ISSUE TITLE
部署出错

### ISSUE THREAD

**Issue by yozman** [vuejs/vue-hackernews-2.0#61]
本地运行没问题
`npm run build`编译之后
将 `index.html` 和 `dist` 目录
上传到了静态服务器，
界面出不来，
控制台显示错误
`Uncaught TypeError: Cannot read property 'route' of undefined`
[线上预览](http://fundo90.com)
该怎么解决呢？

看了代码好像是 `vuex-router-sync` 的问题

**Comment by yyx990803** [comment]
带服务端渲染的 app 不能静态部署。
