### ISSUE TITLE
Implementation without Firebase?

### ISSUE THREAD

**Issue by chuyik** [vuejs/vue-hackernews-2.0#63]
Is it possible to provide a version that implemented with common databases like MongoDB?
I've tried to, but the warning `The client-side rendered virtual DOM tree is not matching server-rendered content.` shows up every refresh and I can't find the answer.
I think I need a example of that, and thanks if possible.

**Comment by yyx990803** [comment]
Hmm, this is not something within the scope of this demo. The API specific parts are already abstracted in `store/api.js` - you can just adapt to different data sources following the same exposed interface.
