### ISSUE TITLE
How to support sass

### ISSUE THREAD

**Issue by billwing** [vuejs/vue-hackernews-2.0#70]
App.vue:

    <style lang="scss">
      @import "sass/app.scss";
    </style>

webpack.base.config.js:

    const path = require('path')
    const vueConfig = require('./vue-loader.config')

    module.exports = {
      devtool: '#source-map',
      entry: {
        app: './src/client-entry.js',
        vendor: ['vue', 'vue-router', 'vuex', 'firebase', 'lru-cache', 'es6-promise']
      },
      output: {
        path: path.resolve(__dirname, '../dist'),
        publicPath: '/dist/',
        filename: 'client-bundle.js'
      },
      module: {
        rules: [
          {
            test: /\.vue$/,
            loader: 'vue',
            options: vueConfig
          },
          {
            test: /\.js$/,
            loader: 'babel',
            exclude: /node_modules/
          },
          {
            test: /\.(png|jpg|gif|svg)$/,
            loader: 'url',
            options: {
              limit: 10000,
              name: '[name].[ext]?[hash]'
            }
          },
          {
            test: /\.scss$/,
            loader: 'style!css!sass',
            exclude: /node_modules/
          }
        ]
      },
      vue: {
        loaders: {
          scss: 'style!css!sass',
          exclude: /node_modules/
        }
      }
    }

That has a error when build the demo:

    throw new WebpackOptionsValidationError(webpackOptionsValidationErrors); 
    WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
    configuration has an unknown property 'vue'. These properties are valid

**Comment by isairz** [comment]
Check https://github.com/vuejs-templates/webpack

**Comment by jiv-e** [comment]
@isairz, I have exactly the same problem. I checked the repo you linked above. I couldn't find anything that would help to solve the issue. I noticed the template is using Webpack 1. The issue is about Webpack 2.  Can you clarify what you meant?

I found this: https://vue-loader.vuejs.org/en/configurations/advanced.html

I think is says we should do something like this inside vue.loader.config.js for Webpack 2...

```
module.exports = {
  postcss: [
    require('autoprefixer')({
      browsers: ['last 3 versions']
    })
  ],
  options: {
    loaders: {
      scss: 'style-loader!css-loader!sass-loader'
    }
  }
}
```
But it results with error: ERROR in ./src/App.vue
Module not found: Error: Can't resolve 'scss' in '/.../vue-hackernews-2.0/src'

If I add this to webpack.base.config.js the error goes away, but styles are not compiled.

const path = require('path')
const webpack = require('webpack') // ADDED THIS.
const vueConfig = require('./vue-loader.config')

module.exports = {
  devtool: '#source-map',
  entry: {
    app: './src/client-entry.js',
    vendor: ['vue', 'vue-router', 'vuex', 'firebase', 'lru-cache', 'es6-promise']
  },
  output: {
    path: path.resolve(__dirname, '../dist'),
    publicPath: '/dist/',
    filename: 'client-bundle.js'
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue',
        options: vueConfig
      },
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'url',
        options: {
          limit: 1000,
          name: '[name].[ext]?[hash]'
        }
      }
    ]
  },
  plugins: [ // ADDED THIS.
    new webpack.LoaderOptionsPlugin({
      options: {
        vue: {
          loaders: {
            scss: 'style-loader!css-loader!sass-loader',
            stylus: 'style-loader!css-loader!stylus-loader'
          }
        }
      }
    })
  ]
}
```

But this seems to override all vue loaders. I needed to add 'stylus' there to get stylus styles working. 

@yyx990803, how to append new loaders without overriding? Is this the preferred method to fix this?

**Comment by isairz** [comment]
I'm sorry I did not have enough explanation. (I am not used to writing English.)

I ported vue-loader options of `https://github.com/vuejs-templates/webpack` to webpack2 version with reference to vue-loader guide. This can load stylus, sass, scss and less.

Try this patch.
https://github.com/isairz/yomiko/commit/af887ea7c9411b17a1886a15253a663048f78ae5


@yyx990803 I think this repo is just simple example, so I didn't pull request about this patch. If you are okay, I want to pull request 'Support sass and less'

**Comment by billwing** [comment]
@isairz THX. I did it in dev through myself. But sassLoader is not work, why?

vue-loader.config:

    const path = require('path')
    const pathToBourbon = require('bourbon').includePaths

    module.exports = {
      postcss: [
        require('autoprefixer')({
          browsers: ['last 3 versions']
        })
      ],
      sassLoader: {
        includePaths: [path.resolve('./src/sass/base'), pathToBourbon]
      },
      loaders: {
        scss: 'style!css!sass',
        exclude: /node_modules/
      }
    }

**Comment by isairz** [comment]
@billwing Could you attach error message?

**Comment by billwing** [comment]
OK, I'm sorry that.

index.vue:

    <style lang="scss">
      @import "bourbon";
    </style>

ERROR:

    Module build failed:
    @import "bourbon";
    File to import not found or unreadable: bourbon

**Comment by isairz** [comment]
@billwing 
Use `@import "~bourbon";`

Read more information *Imports* part of https://github.com/jtangelder/sass-loader

**Comment by billwing** [comment]
@isairz I try this before, but didn't work.

ERROR:
    
    Module build failed:
    var path = require('path');
    Invalid CSS after "v": expected 1 selector or at-rule, was "var path = require("

**Comment by isairz** [comment]
@billwing Great.
That's right solution.

**Comment by jvandenaardweg** [comment]
Was struggelig with this myself. I just needed scss to work. So, I combined some comments here to the minimum working thing with the hackernews files:

On a new hackernews "installation":

```
npm install node-sass style-loader sass-loader --save-dev
```

```js
// /build/vue-loader.config.js
module.exports = {
  preserveWhitespace: false,
  postcss: [
    require('autoprefixer')({
      browsers: ['last 3 versions']
    })
  ],
  loaders: {
    scss: 'style-loader!css-loader!sass-loader',
    exclude: /node_modules/
  }
}
```

```js
// /build/webpack.client.config.js
// Replace the stylus one with this
vueConfig.loaders = {
    scss: ExtractTextPlugin.extract({
      loader: 'style-loader|css-loader!sass-loader',
      fallbackLoader: 'vue-style-loader' // <- this is a dep of vue-loader
    })
  }
```

Re-run `npm run dev` or `npm build`. Now you can use scss.

Hope this helps somebody :)

**Comment by jazoom** [comment]
@jvandenaardweg that's great, thanks! I don't understand why the `loaders` field doesn't need to be in `vue-loader.config.js` for the default stylus implementation and why it doesn't need `style-loader`. It didn't make sense to me why I couldn't get SCSS working.
