### ISSUE TITLE
[webpack2.1.0-beta.26] - Entry module not found: Error: Can't resolve 'babel' in....

### ISSUE THREAD

**Issue by tronghiep92** [vuejs/vue-hackernews-2.0#73]
To day, I new clone project `vue-hackernews-2.0` and I was an error
`Entry module not found: Error: Can't resolve 'babel' in`.
I downgrade webpack version to `webpack2.1.0-beta.25` it worked.
Please help me fix it.

tks!!!!

**Comment by Humeira** [comment]
@tronghiep92 Switched from Babel to Bublé on this one, `pull` from the repo once again.

**Comment by tronghiep92** [comment]
@Humeira tks very much. I saw commit 2d92aa7b093b72e92af476f279c00e4b57e45929
