### ISSUE TITLE
Broken on Internet Explorer 11 (vuex + Promise polyfill woes)

### ISSUE THREAD

**Issue by nickdandakis** [vuejs/vue-hackernews-2.0#79]
```
SCRIPT5022: [vuex] vuex requires a Promise polyfill in this browser.
client-bundle.js (19,1698)
```

Been running into this issue on a website I'm building myself and wanted to see how the official Vue example handles it. Turns out it's broken here too. 

We've used `es6-promise-promise` in a different Vue 2.0 project:
https://www.npmjs.com/package/es6-promise-promise

Specifically
```
new webpack.ProvidePlugin({
    Promise: 'es6-promise-promise', // works as expected
})
```

**Comment by yyx990803** [comment]
I upgraded to u`es6-promise` to 4.x and it now works properly in IE11
