### ISSUE TITLE
How to process protected API with authorization headers ?

### ISSUE THREAD

**Issue by revskill10** [vuejs/vue-hackernews-2.0#80]
In client-side, we could store `access_token` in `localStorage`, but how the server could share that part with client ?

**Comment by ktquez** [comment]
I also have this doubt, I believe that one possibility is using cookie.

Any solution I have, put the solution here.

**Comment by jvandenaardweg** [comment]
There is no other solution. Just don't store it in localStorage, but in a cookie, so the client always sends that in the request to the server.
