### ISSUE TITLE
Could not run well with babel-loader?

### ISSUE THREAD

**Issue by JounQin** [vuejs/vue-hackernews-2.0#81]
Every time when I try to change `buble-loader` to `babel-loader`, it just throws an error:
``` log
TypeError: Cannot read property 'a' of undefined
    at Object.<anonymous> (__vue_ssr_bundle__:6407:114)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.<anonymous> (__vue_ssr_bundle__:10152:63)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at __vue_ssr_bundle__:65:18
    at Object.<anonymous> (__vue_ssr_bundle__:68:10)
    at /local/GitHub/EasyHi/node_modules/vue-server-renderer/build.js:5941:21
    at runInVm (/local/GitHub/EasyHi/node_modules/vue-server-renderer/build.js:5933:10)
    at Object.renderToStream (/local/GitHub/EasyHi/node_modules/vue-server-renderer/build.js:5964:9)
    at app.get (/local/GitHub/EasyHi/server/index.js:75:33)
```

There is no useful error detail for me to fix.

My `.babelrc`:
``` json
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ],
    "stage-0"
  ],
  "plugins": [
    "add-module-exports",
    "transform-runtime"
  ],
  "comments": false
}

```

**Comment by mimani** [comment]
+1

**Comment by scottconrad** [comment]
I believe this might be your syntax.

My entire babelrc is:
```
{
  "presets": ["es2015", "stage-1"],
  "plugins": ["transform-runtime"]
}
I had to install the various things npm complained about not having (babel, babel presets etc.) but otherwise it did work for me. The only other changed is in the webpack.base.config change from buble to babel as the original poster mentioned.

**Comment by JounQin** [comment]
@yyx990803 @scottconrad I find out that this error only occurs when I'm using `babel-plugin-add-module-exports`.

You can use the pure `vue-hackernews-2.0` project and then try to change `buble-loader` to `babel-loader` and  use `.babelrc` as following:
``` json
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ],
    "stage-0"
  ],
  "plugins": [
    "add-module-exports",
    "transform-runtime"
  ]
}
```

**Comment by JounQin** [comment]
After looking through the document of [babel-plugin-add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports#usage), I add `babel-plugin-transform-es2015-modules-umd` in [My Fork of `vue-hackernews-2.0` ](https://github.com/JounQin/vue-hackernews-2.0) and it works!

However, it still occurs another error in my own ssr project [ssr branch](https://github.com/Raiyee/EasyHi/tree/ssr):
> ERROR in ./src/router/index.js
Module build failed: TypeError: /local/GitHub/EasyHi/src/router/index.js: Property consequent of ConditionalExpression expected node to be of a type ["Expression"] but instead got null

Then I just remove `add-module-exports` and `transform-es2015-modules-umd` and it runs well again……

Actually `add-module-exports` is not so useful when combining with `vue-loader` which has smooth the difference of original and new syntax of `require` in `es6 module`.

So I'm going to close this issue because we can just delete the plugin `add-module-exports` and fix this issue.
