### ISSUE TITLE
error loading service-worker

### ISSUE THREAD

**Issue by vedam** [vuejs/vue-hackernews-2.0#82]
Hi,
I cloned/installed the repo. Run with `npm run dev` and got an err loading in browser:

```
A bad HTTP response code (404) was received when fetching the script.    service-worker.js:1
Failed to load resource: net::ERR_INVALID_RESPONSE                service-worker.js
```
As I'm new with vue & co, I don't know where to solve this.

thx

**Comment by yyx990803** [comment]
Service worker is not enabled in dev mode and I cannot reproduce this locally. This message should not affect how the app works, and is unlikely related to the project itself.

**Comment by vedam** [comment]
After starting/restarting the server multiple times again, closing chrome and restarting the computer, the error was gone.

I'm sorry for the noise
and thx for answering

**Comment by slaat** [comment]
for anybody else who is facing this issue, I just had the same problem and found a solution.

Go to 

> chrome://serviceworker-internals/

 and unsubscribe from localhost. 

ServiceWorker is used for push notifications and background sync, see:
https://developers.google.com/web/fundamentals/getting-started/primers/service-workers
