### ISSUE TITLE
buble, buble-loader. you are silly.

### ISSUE THREAD

**Issue by anlexN** [vuejs/vue-hackernews-2.0#84]
@yyx990803 , you are very nice man but also a very silly one. what else make you think of buble better babel ? I'm really can't understanding. Money or your ambition? As for me , using buble surely make me lose time and energy ! I dont want to see you !

**Comment by yyx990803** [comment]
You may not be a nice man, but surely a funny one my friend.

**Comment by srhise** [comment]
wtf
