### ISSUE TITLE
How to know current environment to set apiurl ?

### ISSUE THREAD

**Issue by lijiakof** [vuejs/vue-hackernews-2.0#85]
I have a problem. My website is base on `vue-server-renderer` and use `axios` as http-client. In 'server.js' I use `express-http-proxy` let all `/api/*` proxy to API-Server(http://api-server/). And in `api.js` I must know current env to set axios's `baseURL`, if in browser `baseURL='/api/'`, else if in server `baseURL='http://api-server/'`, but I have so many env(prod\test\gamma\dev), every env has different api url. What should I do?

**Comment by isairz** [comment]
process.env.NODE_ENV or process.env.VUE_ENV ?

**Comment by lijiakof** [comment]
Thanks
