### ISSUE TITLE
Error spread operator when using Bublé

### ISSUE THREAD

**Issue by tronghiep92** [vuejs/vue-hackernews-2.0#87]
I'm using `mapGetters` vuex, to day I converting from Babel to Bublé and
`Object spread operator requires specified objectAssign option with 'Object.assign' or polyfill helper.`
```
computed: {
      ...mapGetters({
           user: 'user'
      })
    },
```
Tks.

**Comment by fandaa** [comment]
Configure this in webpack config file (webpack.base.config.js).
`
module: {
  rules: {
    {
      test: /\.js$/,
      loader: 'buble-loader',
      exclude: /node_modules/,
      options: {
        objectAssign: 'Object.assign'
      }
    },
  }
}
`

**Comment by tronghiep92** [comment]
@fandaa Thanks very much.
But It not working. Default my `webpack.base.config.js`  has the same.

**Comment by fandaa** [comment]
Got the same error. Solved by editing `vue-loader.config.js`
```
module.exports = {
	...
	buble: {
		objectAssign: 'Object.assign',
	},
}
```

**Comment by tronghiep92** [comment]
Tks @fandaa 
I chose to return to Babel :(
