### ISSUE TITLE
How is the performing?

### ISSUE THREAD

**Issue by lijiakof** [vuejs/vue-hackernews-2.0#88]
Can you give some data of performance testing? Such as qps,tps...

**Comment by lijiakof** [comment]
I use loadtest test a simple page with vue ssr, unfortunately the requests per second and latency are more and more bad. what should id do.

$ loadtest -n 1000 http://xxx/test
[Thu Nov 24 2016 04:30:39 GMT+0000 (UTC)] INFO Requests: 0 (0%), requests per second: 0, mean latency: 0 ms
[Thu Nov 24 2016 04:30:44 GMT+0000 (UTC)] INFO Requests: 320 (32%), requests per second: 64, mean latency: 15.6 ms
[Thu Nov 24 2016 04:30:49 GMT+0000 (UTC)] INFO Requests: 498 (50%), requests per second: 36, mean latency: 27.9 ms
[Thu Nov 24 2016 04:30:54 GMT+0000 (UTC)] INFO Requests: 628 (63%), requests per second: 26, mean latency: 38.5 ms
[Thu Nov 24 2016 04:30:59 GMT+0000 (UTC)] INFO Requests: 733 (73%), requests per second: 21, mean latency: 47.6 ms
[Thu Nov 24 2016 04:31:04 GMT+0000 (UTC)] INFO Requests: 820 (82%), requests per second: 17, mean latency: 52 ms
[Thu Nov 24 2016 04:31:09 GMT+0000 (UTC)] INFO Requests: 894 (89%), requests per second: 15, mean latency: 73.8 ms
[Thu Nov 24 2016 04:31:14 GMT+0000 (UTC)] INFO Requests: 962 (96%), requests per second: 14, mean latency: 73.8 ms
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO Target URL:          http://10.5.1.143:12800/test
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO Max requests:        1000
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO Concurrency level:   1
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO Agent:               none
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO Completed requests:  1000
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO Total errors:        0
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO Total time:          38.567144273 s
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO Requests per second: 26
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO Mean latency:        38.5 ms
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO Percentage of the requests served within a certain time
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO   50%      29 ms
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO   90%      56 ms
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO   95%      60 ms
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO   99%      511 ms
[Thu Nov 24 2016 04:31:18 GMT+0000 (UTC)] INFO  100%      666 ms (longest request)

**Comment by yyx990803** [comment]
1. Are you benching this app, or something you wrote yourself? I benched this app on my machine with `ab -n 1000` and the rps is 43.42 with 23ms mean response time:

```
Server Hostname:        localhost
Server Port:            8080

Document Path:          /top
Document Length:        27627 bytes

Concurrency Level:      1
Time taken for tests:   23.030 seconds
Complete requests:      1000
Failed requests:        180
   (Connect: 0, Receive: 0, Length: 180, Exceptions: 0)
Total transferred:      27773180 bytes
HTML transferred:       27627180 bytes
Requests per second:    43.42 [#/sec] (mean)
Time per request:       23.030 [ms] (mean)
Time per request:       23.030 [ms] (mean, across all concurrent requests)
Transfer rate:          1177.72 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:    10   23  25.9     20     294
Waiting:       10   22  24.5     19     294
Total:         10   23  25.9     20     294

Percentage of the requests served within a certain time (ms)
  50%     20
  66%     23
  75%     25
  80%     26
  90%     29
  95%     32
  98%     39
  99%    203
 100%    294 (longest request)
```

2. In real world use cases, you will most likely put an Nginx server in front of this Node app as a reverse proxy to A. directly serve static assets through Nginx & B. leverage Nginx [micro caching](https://www.nginx.com/blog/benefits-of-microcaching-nginx/).

**Comment by lijiakof** [comment]
I benching this app, and benched on my mathine, first time the rps is 49, but second time the rps is 18, 3r time the rps is 9. It looks like worse and worse.

**Comment by lijiakof** [comment]
I use this app on my mathine with loadtest -n 10000, when at 80% the app is crash. And the memory more and more big. I suggest you update the package then have a try, I think it's samething with the memory leak.

**Comment by yyx990803** [comment]
That does sounds like a memory issue, I'll look into it...

**Comment by lijiakof** [comment]
I use `axios` for httpclient, I guess this module has memory problems, when I use it's `interceptors`  the memory usage is increasing, when I dont use it the memory usage is OK. 

And your app use `firebase` has same porblem. But [vue-hackernews-2.0-lazy](https://github.com/Atinux/vue-hackernews-2.0-lazy) Is OK

**Comment by lijiakof** [comment]
And I found `vue-meta` this module also as the same problem.And now I remove `vue-meta` and `axios`'s `interceptors` , the rps is improve to 100. That is great!

**Comment by Hurtak** [comment]
I woul reopen this ticket. Yesterday I was benchmarking server rendered vue and tried to run `wrk` on vue-hackernews-2.0 and I have observed the same performance degradation.

**Comment by lijiakof** [comment]
I think I found the problem, the cache make the performance worse and worse:

src/store/app.js, remove it everything is OK!
```
if (api.cachedIds) {
  warmCache()
}

function warmCache () {
  fetchItems((api.cachedIds.top || []).slice(0, 30))
  setTimeout(warmCache, 1000 * 60 * 15)
}
```
