### ISSUE TITLE
Browserify vs Webpack

### ISSUE THREAD

**Issue by radum** [vuejs/vue-hackernews-2.0#94]
I was wondering what are the benefits of using Webpack for bundling the client and server entries vs using Browserify to do the same thing.

Can anyone share some pointers here?

_Thank you for your answers, just trying to learn._

**Comment by yyx990803** [comment]
Specifically for this demo, nothing in particular. You can use Browserify if that's what you prefer. In the future though we might expand on this to leverage code splitting, which is a feature Browserify does not have.
