### ISSUE TITLE
DOMException: Only secure origins are allowed

### ISSUE THREAD

**Issue by lijiakof** [vuejs/vue-hackernews-2.0#97]
Can I not use service-worker.js? My web has no https.

**Comment by jpca999** [comment]
I too get the same error.  I wonder whats the solution for this ?

**Comment by ram-you** [comment]
During development you'll be able to use service worker through **localhost**, but to deploy it on a site you'll need to have **HTTPS** setup on your server.

https://developers.google.com/web/fundamentals/getting-started/primers/service-workers

**Comment by yyx990803** [comment]
You can just ignore the service-worker errors or comment out service-work registration code in `entry-client.js`.

**Comment by JounQin** [comment]
I use `location.protocol === 'https:' && navigator.serviceWorker && navigator.serviceWorker.register('/service-worker.js')` instead.
