### ISSUE TITLE
npm run dev运行成功，但localhost:8080打不开

### ISSUE THREAD

**Issue by PolanZ** [vuejs/vue-hackernews-2.0#98]
`> vue-hackernews-2.0@ dev F:\GitHub\vue-hackernews-2.0
> node server

server started at localhost:8080
webpack built 996f91e368751fc931e8 in 5953ms
Hash: 996f91e368751fc931e8
Version: webpack 2.1.0-beta.27
Time: 5953ms
        Asset       Size  Chunks             Chunk Names
       app.js     164 kB       0  [emitted]  app
    vendor.js     415 kB       1  [emitted]  vendor
   app.js.map     208 kB       0  [emitted]  app
vendor.js.map     515 kB       1  [emitted]  vendor
   index.html  619 bytes          [emitted]
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  566 kB       0
webpack: bundle is now VALID.`

在 chrome 打开  localhost:8080 挂了。
显示“

> localhost 网页无法正常运作
> 
> localhost 未发送任何数据。

”
console控制台上也没有发现错误。

本地的node -v 是6.5.0
不过webpack是1.13.3的，但依赖安装是2.1.0-beta的应该是这个问题吧。

有人遇到这样的问题吗？

**Comment by bigzhu** [comment]
必须要2.1.0-beta的

**Comment by PolanZ** [comment]
我是说我本地全局是1.13.3版本，但node_module里面是2.1.0-beta版本

**Comment by bigzhu** [comment]
checkout 下来
npm i
npm run
看看能不能运行

**Comment by PolanZ** [comment]
就是这样做的，就是打不开。

**Comment by PolanZ** [comment]
@bigzhu 你的能运行？

**Comment by bigzhu** [comment]
@PolanZ 可以的，只是在应用到自已的spa项目时有不少坑。需要的帮助的话我们单独联系。
在这里聊天似乎不太好

**Comment by Viky-zhang** [comment]
碰到同样的问题~~~checkout 2016-12-16 版本依然~~

**Comment by lincenying** [comment]
目测是国内网络连不上 https://hacker-news.firebaseio.com

**Comment by bigzhu** [comment]
我的没什么问题，而且已在我自已的项目中的部份页面用SSR来应对SEO了

**Comment by leohxj** [comment]
@bigzhu @PolanZ @Viky-zhang 问题解决了吗？我定位发现应该是renderStream的事件没有响应。

@bigzhu renderStream 绑定的 `data`, `end`, `error` 都没有触发， 我感觉是 `vue-server-renderer` 模块的问题，但是不知道该如何定位。能给个思路么。

**Comment by bigzhu** [comment]
@leohxj npm run dev 有报错么?
我的 https://follow.center/ 一直用 vue-ssr 做SEO,没什么问题的

**Comment by leohxj** [comment]
@bigzhu 晚上我在 mac 下试了一下，是没有问题的。下午的时候是 windows 环境。
`npm run dev` 没有报错。

**Comment by leohxj** [comment]
@bigzhu @PolanZ @Viky-zhang 
问题正如 @lincenying 所说，SSR 渲染的时候，网络访问  https://hacker-news.firebaseio.com 异常，阻塞了响应的返回，所以页面一致没有响应。

相关代码在 `src/server-entry.js` 中的 `return component.preFetch(store)`  触发，调用 `src/store/api.js` 中的 `fetch` 方法，最终由于 网络问题 阻塞 `Promise` 返回。

解决的方法，可以使用  `Proxifier` 代理 `node.exe` 使其走一个可用的代理访问请求。

**Comment by Viky-zhang** [comment]
@leohxj 
 https://hacker-news.firebaseio.com
可以举一个具体API正常返回数据的例子么？
如：
URL：
Response：

**Comment by leohxj** [comment]
@Viky-zhang 这个请求貌似不想正常的ajax返回，你可以查看 1.0 的版本，在浏览器端查看它的响应。

[vue-hackernews 1.0](https://github.com/vuejs/vue-hackernews)

**Comment by xz22** [comment]
我觉得是因为电脑里的小文件太多了

**Comment by mniya** [comment]
可以使用 Proxifier 设置下代理就好了

**Comment by HaoChuan9421** [comment]
VPN、代理什么的都关掉，我的影梭使用全局模式就会这样

**Comment by Lamborshea** [comment]
查看 `npm run dev`  的端口是否被占用，比如代理端口，PAC 监听端口，其他服务的运行端口

**Comment by congzhou09** [comment]
> 
> 
> 目测是国内网络连不上 https://hacker-news.firebaseio.com

这个接口现在是不是不公开了？用了代理后在浏览器直接访问“https://hacker-news.firebaseio.com”先提示登录谷歌账号登录后显示“您的操作已遭禁止”

**Comment by congzhou09** [comment]
> 
> 
> > 目测是国内网络连不上 https://hacker-news.firebaseio.com
> 
> 这个接口现在是不是不公开了？用了代理后在浏览器直接访问“[https://hacker-news.firebaseio.com”先提示登录谷歌账号登录后显示“您的操作已遭禁止”](https://hacker-news.firebaseio.com%E2%80%9D%E5%85%88%E6%8F%90%E7%A4%BA%E7%99%BB%E5%BD%95%E8%B0%B7%E6%AD%8C%E8%B4%A6%E5%8F%B7%E7%99%BB%E5%BD%95%E5%90%8E%E6%98%BE%E7%A4%BA%E2%80%9C%E6%82%A8%E7%9A%84%E6%93%8D%E4%BD%9C%E5%B7%B2%E9%81%AD%E7%A6%81%E6%AD%A2%E2%80%9D)

啊可以了 给node设置个能上谷歌的代理之后可以正常跑了
