### ISSUE TITLE
server bundle compile error

### ISSUE THREAD

**Issue by billwing** [vuejs/vue-hackernews-2.0#99]
/vuejs/test/node_modules/vue-slide/vue-slide.vue:1
    (function (exports, require, module, __filename, __dirname) { <style>
    SyntaxError: Unexpected token <

It look like `vue-slide.vue` compile error on the server?

**Comment by chawlaaditya8** [comment]
I am facing the same issue.

Steps to reproduce:

1) Clone the repo.
2) npm install --save vue-pdf
3) Include it in any component.
4) Directly navigate to the route. 

Throws an error

![image](https://user-images.githubusercontent.com/9032537/37444506-f2c629b0-2837-11e8-87fa-9e80cd7d0bcb.png)

**Comment by chawlaaditya8** [comment]
@billwing were you able to solve the issue?

**Comment by billwing** [comment]
@chawlaaditya8 I think that vue-pdf does not support vue-ssr as vue-slide.

**Comment by mryassera** [comment]
> 
> 
> @billwing were you able to solve the issue?

Solve this issue for nuxt.js
👇
#148 (comment)
